/// Flutter icons BottNavIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottNavIcon
///      fonts:
///       - asset: fonts/BottNavIcon.ttf
///
///
///
library;
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class BottNavIcon {
  BottNavIcon._();

  static const _kFontFam = 'BottNavIcon';
  static const String? _kFontPkg = null;

  static const IconData home_outline = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData location = IconData(
    0xf031,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData info_circled_alt = IconData(
    0xf086,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData globe = IconData(
    0xf0ac,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData newspaper = IconData(
    0xf4f0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
